routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', 'FrontController@index')->name('home');
Route::get('/shirts', 'FrontController@shirts')->name('shirts');
Route::get('/shirt', 'FrontController@shirt')->name('shirt');
Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');

Route::get('/home', 'HomeController@index');
Route::resource('/cart', 'CartController');
Route::get('/cart/add-item/{id}', 'CartController@addItem')->name('cart.addItem');

Route::group(['prefix' => 'admin','middleware' => ['auth','admin']], function(){
	Route::get('/', function() {
		return view('admin.index');
	})->name('admin.index');
	Route::resource('product','ProductsController');
	Route::resource('category','CategoriesController');
});
Route::resource('address','AddressController');

//Route::get('checkout', 'CheckoutController@step1');
Route::group(['middleware' => 'auth'], function(){
	Route::get('shipping-info', 'CheckoutController@shipping')->name('checkout.shipping');
});

Route::get('payment', 'CheckoutController@payment')->name('checkout.payment');
Route::post('store-payment', 'CheckoutController@storePayment')->name('payment.store');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
	protected $fillable=['name', 'description', 'size', 'category_id', 'image', 'price'];

    public function category()
    {
    	return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use App\Product;

class ProductsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products=Product::all();
        return view('admin.product.index',compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories=Category::pluck('name', 'id');
        return view('admin.product.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $formInput=$request->except('image');
// validation
        $this->validate($request,[
            'name'=>'required',
            'size'=>'required',
            'price'=>'required',
            'image'=>'required|image|mimes:png,jpg,jpeg|max:10000'
        ]);
// image upload                
        $image=$request->image;
        if($image){
            $imageName=$image->getClientOriginalName();
            $image->move('images', $imageName);
            $formInput['image']=$imageName;
        }


        Product::create($formInput);
        return redirect()->route('product.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/product/create.blade.php
@extends('admin.layout.admin')

@section('content')

	<h3>Add Product</h3>

	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			{!! Form::open(['route' => 'product.store', 'method' => 'post', 'files' => true, 'data-parsley-validate'=>'']) !!}

		<div class="form-group">
			{{ Form::label('name', 'Name') }}
			{{ Form::text('name', null, array('class' => 'form-control', 'required'=>'', 'minlength'=>'5')) }}
		</div>

		<div class="form-group">
			{{ Form::label('description', 'Description') }}
			{{ Form::text('description', null, array('class' => 'form-control')) }}
		</div>

		<div class="form-group">
			{{ Form::label('price', 'Price') }}
			{{ Form::text('price', null, array('class' => 'form-control')) }}
		</div>

		<div class="form-group">
			{{ Form::label('size', 'Size') }}
			{{ Form::select('size', ['small' => 'Small', 'medium' => 'Medium', 'large' => 'Large'], null, ['class' => 'form-control']) }}
		</div>

		<div class="form-group">
			{{ Form::label('category_id', 'Categories') }}
			{{ Form::select('category_id', $categories, null, ['class' => 'form-control', 'placeholder' => 'Select Categories']) }}
		</div>

		<div class="form-group">
			{{ Form::label('image', 'Image') }}
			{{ Form::file('image', array('class' => 'form-control')) }}
		</div>
		{{ Form::submit('Create', array('class' => 'btn btn-success btn-block')) }}
		{!! Form::close() !!}
		</div>
	</div>
@endsection	

resources/views/admin/product/index.blade.php
@extends('admin.layout.admin')

@section('content')

	<h3>Products</h3>

<table class="table">
	@forelse($products as $product)
	<td>
		<h4>Name of product:{{ $product->name }}</h4>
		<h4>Category:{{ count($product->category)?$product->category->name:"N/A" }}</h4>
		<form action="{{ route('product.destroy',$product->id) }}" method="POST">
			{{ csrf_field('DELETE') }}
			{{ method_field('DELETE') }}
			<input class="btn btn-danger btn-sm" type="submit" value="Delete">
		</form>
	</td>

	@empty

	<h3>No products</h3>
	
	@endforelse
</table>

@endsection